### ISSUE TITLE
Submission Template

### ISSUE THREAD

**Issue by adekunleoduye** [GothamSass/centralpark#1]
You can copy the raw template [here](https://raw.githubusercontent.com/GothamSass/centralpark/master/docs/talk-proposal-template.md)
# Title of Presentation (required)
## Type of Presentation (required)

[  ] Standard Length Talk _(20 or 30 mins)_
[  ] Lightning Talk _(5 or 10 mins)_
[  ] Workshop _(1.5-3hrs)_
- Please list max attendance
## When would you ideally like to speak

_list a month_
## Description (required)

[A description of your presentation goes here. Please don't give us a 140 character elevator pitch—tell us what you want to talk about. Give us an outline. Bullet points. A long rambly description of an idea. Tell us your dreams.
## Speaker Info (required)
- Name                     : Bruce Wayne
- Location                 : Gotham, NY
- Contact                  : bruce@wayne.com
- Preferred gender pronoun   : They/Them/She/Her/Him/He
##### Social Media:
- Twitter   : [@iambatman](url to twitter account)
- GitHub    : [iambatman](url to GitHub account)
- Url(s)    : [iambatman.com](url to relevant sites)
##### Bio:

I’m an example bio. I'm an Billionaire CEO by day and a cape crusader by night. I AM BATMAN!
##### Photo:

![Avatar](http://www.tvsinopse.kinghost.net/ebook2/batman63_arquivos/tvsinopse20199249.jpg)

_replace with your URL_

_Photo/Art by [Osama](http://www.tvsinopse.kinghost.net/ebook2/batman63.htm)._

---

**Comment by misscs** [comment]
Made a couple updates to the template
- Changed preferred gender to preferred gender pronoun
- Add a section for speakers to tell us when they'd like to speak

**Comment by adekunleoduye** [comment]
hey @HipsterBrown, this is a submission template you can use to give us details for your presentation. Just create a new issue and edit the [template](https://raw.githubusercontent.com/GothamSass/centralpark/master/docs/talk-proposal-template.md) with you info. 

Thanks!

**Comment by HipsterBrown** [comment]
Done! :raised_hands: 
->  #4
