### ISSUE TITLE
Tab Promised Me This Will Work (an intro to Houdini)

### ISSUE THREAD

**Issue by Snugug** [GothamSass/centralpark#11]
# Tab Promised Me This Will Work (an intro to Houdini)
## Type of Presentation
- [x] Standard Length Talk _(20 or 30 mins)_
- [ ] Lightning Talk _(5 or 10 mins)_
- [ ] Workshop _(1.5-2hrs)_
## When would you ideally like to speak
- April
- May
## Description

An introduction to what you can look forward to with [CSS Houdini](https://wiki.css-houdini.org/), an upcoming extension to how CSS gets rendered providing new and awesome power to end-users. It will be a high-level overview and a specific exploration of how one could go about and create a new custom `@rule` (element queries anyone?) using Houdini.
## Speaker Info
- Name                     : Sam Richard
- Location                 : Gotham, NY
- Contact                  :  sam [at] snug [dot] ug
- Preferred gender pronoun   : He/Him
##### Social Media:
- Twitter   : [@snugug](https://twitter.com/snugug)
- GitHub    : [snugug](https://github.com/snugug)
- Url(s)    : [snugug.com](https://snugug.com)
##### Bio:

https://snugug.com/me/

**Comment by skyfaerie** [comment]
Hey @Snugug! Thanks for submitting talk proposal! We'll be in touch soon.

**Comment by skyfaerie** [comment]
Hey @Snugug, your talk has been scheduled! Here's the link: 
http://www.meetup.com/gothamsass/events/229473121/
Let us know if there are any changes/updates needed.
