### ISSUE TITLE
Bridging the gap between design & development

### ISSUE THREAD

**Issue by acacheung** [GothamSass/centralpark#12]
# Bridging the gap between design & development
## Type of Presentation (required)
- [x] Standard Length Talk _(20 or 30 mins)_
- [ ] Lightning Talk _(5 or 10 mins)_
- [ ] Workshop _(1.5-2hrs)_
## When would you ideally like to speak

May
## Description (required)

Designers and developers often have specific goals when creating interactive experiences. Because our creative processes overlap and influence one another, knowing each other’s considerations is key to designing and implementing experiences that are both usable and performant. How can designers help developers? How can developers help designers? In this presentation, we will explore communication and collaboration practices that help in this process.

A link to the [slides](http://slides.com/amandacheung/bridging-the-gap)!
## Speaker Info (required)
- Name                     : Amanda Cheung
- Location                 : Boston, MA
- Contact                  : acacheung@gmail.com
- Preferred gender pronoun   : She/Her/Hers
##### Social Media:
- Twitter   : [@acacheung](https://twitter.com/acacheung)
- GitHub    : [acacheung](https://github.com/acacheung)
##### Bio:

Amanda is the lead UX developer at DockYard. She is always trying to improve the designer-developer relationship. Passionate about accessibility and CSS architecture, Amanda is also a co-organizer of the Boston CSS Meetup, an adjunct professor at MassArt and a teacher for Girl Develop It.
##### Photo:

![Avatar](https://pbs.twimg.com/profile_images/596398203685081088/1YHFjsPS.jpg)

**Comment by adekunleoduye** [comment]
Thanks for submitting a talk proposal @acacheung! We actually have a talk scheduled for May, can you do June?

**Comment by acacheung** [comment]
Thanks! I can't do June, but how about July?

**Comment by adekunleoduye** [comment]
July works....We usually have the meetup on the last Tuesday of the month. Does July 26th work for you?

**Comment by acacheung** [comment]
It does!

**Comment by adekunleoduye** [comment]
@acacheung, your talk has been scheduled for July 26th.
Check it out here: http://www.meetup.com/gothamsass/events/229607375/

Let use know if you have any questions....thanks again!

**Comment by acacheung** [comment]
Awesome thank you!
