### ISSUE TITLE
The Recipe for Building a Great Prototype

### ISSUE THREAD

**Issue by adekunleoduye** [GothamSass/centralpark#13]
# The Recipe for Building a Great Prototype
## Type of Presentation (required)
- [x] Standard Length Talk _(20 or 30 mins)_
- [ ] Lightning Talk _(5 or 10 mins)_
- [ ] Workshop _(1.5-2hrs)_
## When would you ideally like to speak

_Whenever_
## Description (required)

Today’s designers have more responsibilities than ever. Our jobs are more than how an application looks but also creating useful interactions that add to the user experience. There are many products out here that assist designers conceptualizing user interactions and workflows in little time but the problem is being able to validate these experience before the product is launched. So, how can we test out our application without disrupting the design process? Enter the Prototype....
## Speaker Info (required)
- Name                     : Adekunle Oduye
- Location                 : New York, NY
- Contact                  : adekunleoduye@gmail.com
- Preferred gender pronoun   : He
##### Social Media:
- Twitter   : https://twitter.com/adekunleoduye
- GitHub    : https://github.com/adekunleoduye
- Url(s)    :http://www.adekunleoduye.com/
##### Bio:

Adekunle Oduye is a Product Designer at Nasdaq OMX, where he’s part of a 30 person team designing web-based products that serve communications, public relations, and investor relations professionals. Adekunle main skill-set includes interaction/user interface design and front-end development….making him the ultimate weapon! Outside of Nasdaq, Adekunle is a co-organizer for SassConf and GothamSass Meetup, which serves front-end developers, CSS ninjas, UX mavens, and lovers for the best css-preprocessor. When he’s not creating cool software you can probably find him traveling the world or exploring the streets of New York City.
##### Photo:

![me](https://cloud.githubusercontent.com/assets/2554297/15718905/8a4e2b0a-27fb-11e6-8c93-4332ef756d65.jpg)

**Comment by rabellamy** [comment]
👍
