### ISSUE TITLE
Modular Design: Developing, Maintaining, and Extending Component-Based CSS

### ISSUE THREAD

**Issue by erindepew** [GothamSass/centralpark#14]
# Modular Design: Developing, Maintaining, and Extending Component-Based CSS
## Type of Presentation (required)
- [X] Standard Length Talk _(20 or 30 mins)_
- [ ] Lightning Talk _(5 or 10 mins)_
- [ ] Workshop _(1.5-2hrs)_
## When would you ideally like to speak

June or August
## Description (required)

Component-based web development is a movement that has been gaining popularity in the front-end development community, but too often developers don’t apply the same principles to their CSS. At Bitly, we are using a hybrid approach for our CSS-preprocessor which draws inspiration from BEM, SMACSS, and OOCSS in order to create modular, reusable Sass-based “components”. In this talk I’ll discuss how we wrangled our Sass to align with our React components, as well as the benefits and drawbacks we encountered while taking this approach. 
## Speaker Info (required)
- Name                     : Erin Depew
- Location                 : New York, NY
- Contact                  : erinldepew@gmail.com
- Preferred gender pronoun   : She
##### Social Media:
- Twitter   : [@erindepew](https://twitter.com/erindepew)
- GitHub    : [erindepew](https://github.com/erindepew)
##### Bio:

Erin is a front-end engineer at Bitly who is working on making the web a more beautiful place one website at a time and appreciates an epic CSS hack every now and again. 
##### Photo:

![Avatar](http://bit.ly/1SANGhlx)

**Comment by adekunleoduye** [comment]
Hey @erindepew!

Thanks for your submission! Your talk sounds very interesting. 
I was wondering if June 28th would work for you?

**Comment by erindepew** [comment]
Yes, June 28th works for me!

**Comment by adekunleoduye** [comment]
Great!

You're all set: http://www.meetup.com/gothamsass/events/231969030/

Please let me know if you need anything and see you on June 28th!
