### ISSUE TITLE
Coding for Accessibility

### ISSUE THREAD

**Issue by KamillaKhabibrakhmanova** [GothamSass/centralpark#15]
# Coding for Accessibility
## Type of Presentation (required)
- [x] Standard Length Talk _(20 or 30 mins)_
- [ ] Lightning Talk _(5 or 10 mins)_
- [ ] Workshop _(1.5-2hrs)_
## When would you ideally like to speak

Whenever
## Description (required)

Making sure that your web application is optimized for users with visual impairments is important from both a legal and a growth perspective. Moreover, many of the guidelines are simply standard good coding practices that we may forget in our day-today coding and are not hard to implement once we remember to keep them in mind. First, I'd like to share some arguments for prioritizing accessibility during development, from both legal perspectives and from the perspective of the potential share of web users you may be using by not taking accessibility into account. Then I would like to pinpoint the most important steps you can take to make sure your code is accessible to as many users as possible, highlighting essential tools to put in your developer kit along the way. Finally, I'd like to share some examples of non-optimized and well-optimized sites to give a feel of how much these best practices can enhance the user experience.
## Speaker Info (required)
- Name                     : Kamilla Khabibrakhmanova
- Location                 : Brooklyn, NY
- Contact                  : venessiel@gmail.com
- Preferred gender pronoun   : She
##### Social Media:
- Twitter   : [@kabibster]
- GitHub    : [kamillakhabibrakhmanova]
- Url(s)    : [kamilla.io]
##### Bio:

Kamilla is a Software Engineer at GLAMSQUAD, where she creates things using NodeJS and AngularJS. In her spare time she loves participating in hackathons, going to meetups, and discovering new wines.
##### Photo:

![Avatar](http://www.tvsinopse.kinghost.net/ebook2/batman63_arquivos/tvsinopse20199249.jpg)

_replace with your URL_

_Photo/Art by [Osama](http://www.tvsinopse.kinghost.net/ebook2/batman63.htm)._

**Comment by adekunleoduye** [comment]
Hey @KamillaKhabibrakhmanova 

Thanks for your submission! Nice to see a talk about accessibility.

Will Tuesday, August 30th work for you?

**Comment by KamillaKhabibrakhmanova** [comment]
Hey @adekunleoduye 

Sorry....got really busy the past couple of weeks. I am actually going to give the same talk at a conference in late November, would love to do it a meetup closer to the event as a test run. Do you have any dates for October/ beginning to mid-November?

**Comment by skyfaerie** [comment]
No worries! We have an October talk already, and are considering going on break for November/December for the holidays. September 27 is really our only sure open date right now. We can switch a our November 10 open hacknight @ pivotal labs for a lecture night if that works for you.
