### ISSUE TITLE
How to win maintainability and influence coworkers with Expressive CSS

### ISSUE THREAD

**Issue by akdetrick** [GothamSass/centralpark#16]
# How to win maintainability and influence coworkers with Expressive CSS
## Type of Presentation (required)
- [x] Standard Length Talk _(20 or 30 mins)_
- [ ] Lightning Talk _(5 or 10 mins)_
- [ ] Workshop _(1.5-2hrs)_
## When would you ideally like to speak

Between 10/2016 and 12/2016
### Summary

Using real-world examples, I will show you how the "Expressive CSS" paradigm will help others understand and enjoy working with your code. 

Let's challenge conventional wisdom together to make the experience of working with CSS better for everyone! Only basic knowledge of CSS is necessary; this talk is recommended for beginners and experts alike.
### Detail

Think about the last time you had to work with CSS that someone else wrote. Could you understand their intention by reading the CSS and markup without loading it up in a browser? What about code that you wrote over a year ago?

Creating a good experience doesn't have to be limited to our users. There are CSS techniques we can apply to provide usability to our fellow developers.

Years of building CSS frameworks has given me the opportunity to see which approaches fail when it comes to writing CSS intended for other developers. At my company, we've successfully settled on a CSS paradigm recently described by John Polacek as [Expressive CSS](http://johnpolacek.github.io/expressive-css/).

I'll explain Expressive CSS through real-world examples that demonstrate how this technique has helped us build layouts faster with less bugs, less duplication, and a better understanding of how style rules are being applied.

Developing a "best practice" is an iterative process; we already have great ideas like SMACSS and OOCSS, but it's important to keep the conversation going so we can build on these concepts. Come with an open mind, and I'll show you how a class-heavy approach, while somewhat controversial, has made us a happier and more effective development team.
## Speaker Info (required)
- Name                     : Adam Detrick
- Location                 : Brooklyn, NY
- Contact                  : akdetrick@gmail.com
- Preferred gender pronoun   : He
##### Social Media:
- Twitter   : [@akdetrick](http://twitter.com/akdetrick)
- GitHub    : [akdetrick](http://github.com/akdetrick)
- Url(s)    : [meetup](meetup.com)
##### Bio:

TK
(avatar TK)
##### More info

This is my submission to CSS Conf Australia. This is a talk I'd like to bring to Gotham Sass either way, if there's interest.

**Comment by adekunleoduye** [comment]
Hey @akdetrick

Thanks for your submission! Haven't heard of Expressive CSS before...looks like an interesting concept.

Does Tuesday, October 25th work for you?

**Comment by akdetrick** [comment]
Thanks, that works for me!

**Comment by adekunleoduye** [comment]
@akdetrick, your talk has been scheduled for October 25th. Check it out here: https://www.meetup.com/gothamsass/events/233087602/

Let use know when you have a bio and avatar for the site.

Thanks!
