### ISSUE TITLE
The Modular Grid — a Chrome Extension in Beta

### ISSUE THREAD

**Issue by code-warrior** [GothamSass/centralpark#17]
# The Modular Grid — a Chrome Extension

## Type of Presentation
- [ ] Standard Length Talk *(20 or 30 mins)*
- [x] Lightning Talk *(5 or 10 mins)*
- [ ] Workshop *(1.5-2hrs)*

## When would you ideally like to speak
_April or May 2017_, on a Tuesday or Friday evening, which are my only two free evenings during the week.

## Description

In the translation of design mocks to working web pages, web developers tend to make many visual positional guesses in the process that alter a designer’s original design intentions. However, when a modular grid — one comprised of both a column and baseline grid — is used by both design and development, it’s easier for web developers to remain true to original designs. Furthermore, combined with a CSS preprocessor like Sass, it becomes very possible to achieve true, near pixel-perfect translations of designs into web pages.

Therefore, I’d like to talk about [The Modular Grid](), an open source Chrome extension in beta that overlays, or superimposes, a grid over web pages. Because this project is in beta, I would be delighted to get UI and design feedback from the community, and also take feature requests.

## Speaker Info

* Name : **Roy Vanegas**
* Location : **Queens, NY**
* Contact : `roy dot vanegas at gee mail dot com`
* Preferred gender pronoun : **He**

##### Social Media:

* Twitter : [@royvanegas](https://twitter.com/royvanegas) — I never use this
* GitHub  : [code-warrior](https://github.com/code-warrior) — I always use this

##### Bio:

I’m an educator, animal rights activist, and full stack engineer specializing in front end, public-facing technologies, such as Sass and JavaScript. I teach at schools as varied as BMCC and RISD, and I’ve worked at places as varied as NYU and IBM. I shepherd two dogs and two rats, all of whom get along swimmingly.

##### Photo:

![Avatar](http://roy.vanegas.org/img/me.jpg)

_Photo by Joanne Madden_

**Comment by skyfaerie** [comment]
Hello Roy! Thanks for reaching out! Our dates for those months are April 24th and May 30th, both Tuesdays. April would be great, but have both available until we confirm something. :-)
If you're good with April, I'll go ahead and book that.

**Comment by code-warrior** [comment]
I’m afraid 24 April is no good, as I’m teaching that evening. (I teach this semester on Monday, Wednesday, and Thursday evenings.) The 30th of May, however, is fine. (smiley face)

**Comment by skyfaerie** [comment]
You're scheduled! RSVPs open two weeks beforehand (I'm trying a new thing here for accurate attendee count), so I'll be closing this issue. Don't hesitate to reach out to me if you need anything before then! 
https://www.meetup.com/gothamsass/events/237987490/
