### ISSUE TITLE
Improving interactivity for legacy front-end applications using Vue.js

### ISSUE THREAD

**Issue by dhartunian** [GothamSass/centralpark#18]
# Improving interactivity for legacy front-end applications using Vue.js 

## Type of Presentation (required)
- [X] Standard Length Talk *(20 or 30 mins)*
- [ ] Lightning Talk *(5 or 10 mins)*
- [ ] Workshop *(1.5-2hrs)*

## When would you ideally like to speak
Anytime is fine

## Description (required)

* Based on material I wrote about here: https://medium.com/position-development-blog/give-vue-js-a-shot-if-youre-adding-interactivity-to-a-traditional-web-app-879c8e99b51c
* Topics I would like to cover
  * Difficulties with migrating large legacy apps to fancy new frameworks like React
  * My experience with using Vue as a quick drop-in replacement for snippets of jQuery
  * Discussion of why Vue is easy to get started with and why I'd like to keep using it
  * Experience with pairing on Vue.js with designers
* Goal is to inspire people to replace some scary jQuery they deal with semi-regularly and always dread

## Speaker Info (required)

* Name                     : David Hartunian
* Location                 : Brooklyn, NY
* Contact                  : david@musicismath.net
* Preferred gender pronoun   : Him/He

##### Social Media:

* Twitter   : [@musicismath](https://twitter.com/musicismath)
* GitHub    : [dhartunian](https://github.com/dhartunian)
* Url(s)    : [Position Development](http://positiondev.com)

##### Bio:

David is a programmer who enjoys working on user-facing software and collaborating closely with clients.

Over the course of 8 years in the industry, David gained experience solving problems through software for finance and education. He most recently spent 3 years building educational technology software at Knewton where he was involved in all aspects of technical planning and implementation including data modeling, user research, and frontend design.

David currently works at Position Development where he is a full-stack developer, and occasional project manager. He enjoys supporting the work of Position's clients and being part of its strongly collaborative culture.

##### Photo:

![Avatar](https://s.gravatar.com/avatar/5b8f0b080141a163211d0bab2cc984d1?s=80)

**Comment by adekunleoduye** [comment]
Hey @dhartunian

Thanks for your submission! Vue.js would be a great topic to cover at the meetup.

I know this is a late notice but would you be available to give the talk next **Tuesday, April 25th** at 7pm?

**Comment by dhartunian** [comment]
Assuming you mean April, I think I can do it. Put me on the schedule!

What do you need from me before then?

**Comment by adekunleoduye** [comment]
@dhartunian Ah...sorry about that! Yes, **Tuesday, April 25th**. 

I think the information you provided above is enough for right now. Will let you know when the meetup is scheduled.

Thank you so much!!

**Comment by adekunleoduye** [comment]
@dhartunian Meetup has been announced: https://www.meetup.com/gothamsass/events/239327017/

Let me know if you have any questions of concerns.

Thanks again!
