### ISSUE TITLE
Webpack Blues

### ISSUE THREAD

**Issue by copasetickid** [GothamSass/centralpark#19]
# Title of Presentation (required)
Webpack Blues

## Type of Presentation (required)
- [x ] Standard Length Talk *(20 or 30 mins)*
- [ ] Lightning Talk *(5 or 10 mins)*
- [ ] Workshop *(1.5-2hrs)*

## When would you ideally like to speak
July

## Description (required)

Webpack has become one of the most important tools for modern web development.Primarily it’s a module bundler for your JavaScript but it can be taught to transform all of your front-end assets like HTML and CSS, even images. This talk will be a deep dive into getting started and working with Webpack for various aspects of front-end work. 

## Speaker Info (required)

* Name                     : Rushaine McBean
* Location                 : New York
* Contact                  : rushaine.mcbean@gmail.com 

##### Social Media:

* Twitter   : [@copasetickid](https://twitter.com/copasetickid)
* GitHub    :[copasetickid](https://github.com/copasetickid)

##### Bio:

Rushaine McBean is a software engineer who specializes in building JavaScript and Ruby on Rails web applications. She picked up JavaScript as her first web technology then Ruby on Rails to serve as her API and hasn’t looked back. When she’s not writing code for she’s working on side projects to stay update to with JavaScript & Ruby on Rails technologies or helping run Manhattan.js a local JS meetup in NYC.

##### Photo:

![Avatar](https://pbs.twimg.com/profile_images/3335554289/9d0acf9e5b895a38e186ffab8125854c_400x400.jpeg)

**Comment by skyfaerie** [comment]
You're scheduled! https://www.meetup.com/gothamsass/events/241300574/
