### ISSUE TITLE
Why the Designer Failed FizzBuzz

### ISSUE THREAD

**Issue by laras126** [GothamSass/centralpark#2]
# Why the Designer Failed FizzBuzz
## Type of Presentation
- [x] Standard Length Talk _(20 or 30 mins)_
- [ ] Lightning Talk _(5 or 10 mins)_
- [ ] Workshop _(1.5-2hrs)_
## Description

I’m one of those hybrid designer/developers. Unicorn? No. I failed FizzBuzz in an interview as a result of a self-taught skill-set and an ambiguous job posting. Does that mean I’m not a “real” developer? To some yes, to others no. Then what do I call myself? Am I a liar, a fake? Whatever the case, I’m not alone here.

This isn’t the impostor syndrome. It’s the result of an industry in its awkward twenties; it’s identity crisis and it’s ego. We aren’t fakes, we just don’t know how to accurately communicate our skills. In this talk, I’ll start by reviewing the heated responses to [an article I wrote](https://css-tricks.com/tales-of-a-non-unicorn-a-story-about-the-trouble-with-job-titles-and-descriptions/) about the above scenario. Then I’ll propose a four part lexicon for job titles and descriptions in the web industry; a vocabulary that both standardizes our roles, yet allows for the rapidly changing nature of what we do. Whether or not my lexicon is the one that works, let’s start talking about it.
#### Takeaways:
- A call to be more conscious of terminology in job postings, and suggestions for simple changes to descriptions.
- Evaluating candidates’ qualifications: getting away from the idea of a “checklist”, focusing more on a capacity to learn, passion for the craft, and community participation.
- A system of terms and definitions (lexicon) for job postings where all job titles follow a three part structure:
  1. Junior, Mid-level, or Senior
  2. Skill-set (e.g. backend, frontend, UX, etc.)
  3. Generalist or Specialist
- Start a conversation around the standardization of job titles and descriptions.
- Propose a structured way to format job postings.
## Speaker Info
- Name                     : Lara Schenck
- Location                 : NY, NY
- Contact                  : lara@notlaura.com
- Preferred gender   : Female
##### Social Media:
- Twitter: [@laras126](http://twitter.com/laras126)
- Website: [notlaura.com](http://notlaura.com)
- Github: [laras126](http://github.com/laras126)
##### Bio:

Lara Schenck is an independent web consultant and teacher in New York City. She teaches front-end development to designers at Pratt Institute, facilitates corporate trainings with [Decoded](http://decoded.com), and organizes private classes and workshops. Lara is a dedicated cocktail enthusiast and grew up on a llama farm outside of Pittsburgh (true story).
##### Photo:

![Lara!](http://stuff.notlaura.com/images/headshot.png)

**Comment by misscs** [comment]
:+1: 

When would you like to speak? July we meet on the 21st and starting in August we're moving to the 4th Tuesday of the month

**Comment by laras126** [comment]
Yes yes yes! The 21st is great.

On Sat, Jun 27, 2015 at 3:56 PM, claudina sarahe notifications@github.com
wrote:

> [image: :+1:]
> 
> When would you like to speak? July we meet on the 21st and starting in
> August we're moving to the 4th Tuesday of the month
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GothamSass/centralpark/issues/2#issuecomment-116123671
> .

## 

Lara Schenck
Web Design + Education
notlaura.com

@laras126 https://twitter.com/laras126 (on occasion)

**Comment by laras126** [comment]
Oh, can we update the meet up page too? Was going to tweet about it, etc.

On Mon, Jun 29, 2015 at 9:43 AM, Lara Schenck lara@notlaura.com wrote:

> Yes yes yes! The 21st is great.
> 
> On Sat, Jun 27, 2015 at 3:56 PM, claudina sarahe <notifications@github.com
> 
> > wrote:
> > 
> > [image: :+1:]
> > 
> > When would you like to speak? July we meet on the 21st and starting in
> > August we're moving to the 4th Tuesday of the month
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/GothamSass/centralpark/issues/2#issuecomment-116123671
> > .
> 
> ## 
> 
> Lara Schenck
> Web Design + Education
> notlaura.com
> 
> @laras126 https://twitter.com/laras126 (on occasion)

## 

Lara Schenck
Web Design + Education
notlaura.com

@laras126 https://twitter.com/laras126 (on occasion)

**Comment by laras126** [comment]
Heyo! Let's actually move this to August 25th - would like to promote it a bit beforehand if possible :+1:

**Comment by misscs** [comment]
YES! agreed. Will get it up on the site and meetup page this weekend.

On Fri, Jul 17, 2015, at 13:58, Lara Schenck wrote:

> Heyo! Let's actually move this to August 25th - would like to promote
> it a bit beforehand if possible :+1:
> 
> — Reply to this email directly or view it on GitHub[1].

Links:
1. https://github.com/GothamSass/centralpark/issues/2#issuecomment-122357307

**Comment by adekunleoduye** [comment]
@laras126 & @misscs I just updated the meetup page. Here is the link: http://www.meetup.com/gothamsass/events/224009907/
