### ISSUE TITLE
JavaScript Prototypal Inheritance — a Brief Introduction

### ISSUE THREAD

**Issue by code-warrior** [GothamSass/centralpark#20]
# JavaScript Prototypal Inheritance — a Brief Introduction

## Type of Presentation

- [x] Standard Length Talk *(20 or 30 mins)*
- [ ] Lightning Talk *(5 or 10 mins)*
- [ ] Workshop *(1.5 – 2hrs)*

## When would you ideally like to speak?

Thursday, 21 September 2017

## Description

Prototypal inheritance is an important feature of JavaScript — it allows users the ability to override methods in the prototype chain. It’s often overlooked, yet very helpful. Let’s talk protoypal inheritance so you can better prepare your next JavaScript project, or just better prepare your next interview.

## Speaker Info

* Name : **Roy Vanegas**
* Location : **Queens, NY**
* Contact : `roy dot vanegas at gee mail dot com`
* Preferred gender pronoun : **He**

##### Social Media:

* GitHub: [code-warrior](https://github.com/code-warrior) — I always use this
* Twitter: [@royvanegas](https://twitter.com/royvanegas) — I rarely use this

##### Bio:

I’m an educator, animal rights activist, and full stack engineer specializing in front end, public-facing technologies, such as Sass and JavaScript. I teach — or have taught — at schools as varied as BMCC and Columbia University and I’ve worked at places as varied as NYU and IBM.

##### Photo:

![Avatar](http://roy.vanegas.org/img/roy-vanegas--756x756.png)

_Photo by Tova Borowski_

**Comment by skyfaerie** [comment]
This talk has been scheduled! https://www.meetup.com/gothamsass/events/243179466/
