### ISSUE TITLE
Nick Hehr - Collaborative Style Syntax

### ISSUE THREAD

**Issue by HipsterBrown** [GothamSass/centralpark#4]
# Collaborative Style Syntax
## Type of Presentation (required)
- [x] Standard Length Talk _(20 or 30 mins)_
- [ ] Lightning Talk _(5 or 10 mins)_
- [ ] Workshop _(1.5-2hrs)_
## When would you ideally like to speak

October
## Description (required)

Sharing CSS among designers, front-end devs, and back-end devs can be a tricky business. One of the biggest issues with this can be communication. What kind of system enables designers to clarify their concepts with developers while directly translating to CSS? I'll speak about:
- the concept of functional CSS 
- how it helps solve problems at Namely 
- how it boosts performance & efficiency among every team

Everyone cares about style and design in some way or another, so taking the time to build a jargon helps everyone communicate that caring and push a project forward. 
## Speaker Info (required)
- Name                     : Nick Hehr
- Location                 : New York, NY
- Contact                  : headhipster@hipsterbrown.com
- Preferred gender pronoun   : Him/He
##### Social Media:
- Twitter   : [@hipsterbrown](https://twitter.com/hipsterbrown)
- GitHub    : [hipsterbrown](https://github.com/hipsterbrown)
- Url(s)    : [more-empathy.online](http://more-empathy.online)
##### Bio:

I’m an an empathetic community member, front-end developer, and avid Disney parks & animation fan. When I'm not at a meetup or contributing to [Hoodie](http://hood.ie), you can probably find me at the nearest climbing gym. My mustache is real and has been growing on me for over two and a half years.
##### Photo:

![Avatar](https://pbs.twimg.com/profile_images/378800000092843684/53d860b8732da91dbf064765cb3ea696_200x200.jpeg)

_hipsterbrown.com_

---

**Comment by rabellamy** [comment]
:+1:

**Comment by adekunleoduye** [comment]
@HipsterBrown: Thanks for doing this! October's meetup will happen on Oct 27th at 7pm.

Is that good for you?

**Comment by HipsterBrown** [comment]
That works for me. :+1:
