### ISSUE TITLE
Push left to win: building the future of CSS grids

### ISSUE THREAD

**Issue by whmii** [GothamSass/centralpark#6]
Push left to win: building the future of CSS grids

Type of Presentation
- [X] Standard Length Talk (20 or 30 mins)
- [ ] Lightning Talk (5 or 10 mins)
- [ ] Workshop (1.5-3hrs)

Max Attendance: N/A
When would you ideally like to speak: whenever

Description 

Float grids are awesome! Like REALY AWESOME! there are lots of different types of all shapes and sizes, and we'll hit them all to understand where we are. And then we'll take a look at the future.

Speaker Info (required)

Name : Will H McMahan
Location : Gotham, NY
Contact : will@mcmahan.me
Preferred gender pronoun : HE/HIM
More Info (optional) : 

Social Media:

Twitter : @whmii
GitHub : whmii
Url(s) : mcmahan.me
Bio: An experience designer from living and eating in New York. Creating the future in digital worlds, big and small.

Photo:
https://www.dropbox.com/s/bgds6jtlzr8ydvd/1511377_10153604946800277_2068091574_n.jpg?dl=0

**Comment by whmii** [comment]
yeap

**Comment by whmii** [comment]
…

**Comment by skyfaerie** [comment]
Hey Will! Thanks for being so patient! This is happening! We'll shoot you an email by end of week. :-)

**Comment by skyfaerie** [comment]
Here's the link to your talk right now.
What do you think? 
http://www.meetup.com/gothamsass/events/228985498/

**Comment by whmii** [comment]
@skyfaerie Cool, thx. can you update description to:

> Float grids are awesome! Like REALY AWESOME! There are lots of different types of all shapes and sizes, and we'll hit them all to understand what makes them tick, and then take a look at the future of grids.

**Comment by skyfaerie** [comment]
done! meetup announced! closing ticket.
