### ISSUE TITLE
Intro to Git

### ISSUE THREAD

**Issue by rabellamy** [GothamSass/centralpark#7]
# Intro to Git
## Type of Presentation (required)
- [ ] Standard Length Talk (20 or 30 mins)
- [ ] Lightning Talk (5 or 10 mins)
- [X] Workshop (1.5-3hrs)
## When would you ideally like to speak

April
## Description (required)

A hands-on intro to Git and collaborating on a team with Git.

[Git](https://git-scm.com/) is an open source and free Source Code Management System (SCM) (a.k.a, Revision Control System or 'the stupid content tracker'). It is used to store your code (or any documents really) and manage the versions of that code through the development lifecycle. More specifically, it’s a Distributed Revision Control System, which means when you have a copy of the code, you actually have a copy of the entire repository.
- **Speed**: Git is very fast!
- **Forks, Branches and Merging**: work on copies of code and merge when your new work is stabilized.
- **History**: track the history of code over its lifespan.
- **Work Online or Offline**: Git keeps the entire repository locally on your machine so you can work online and even when you're offline (commits and all).
- **Collaboration**
- **Popularity and Community Support**: Git is easy, it’s also supported by innumerable tools and services and has become something of a de facto standard.
- **Git is a flexible and powerful, used in many different ways**. 

Topics include but not limited to:
- installing Git
- Git basics
- Git swagger
- practicing good Git hygiene
- playing nicely with others
- Github basics
- contributing to open source
## Speaker Info (required)
- Name                     : Robert Anthony Bellamy
- Location                 : New York, NY
- Contact                  : rabellamy@gmail.com
- Preferred gender pronoun   : Him/He
##### Social Media:
- Twitter   : [rabellamy](https://twitter.com/rabellamy)
- GitHub    : [rabellamy](https://github.com/rabellamy)
- LinkedIn    : [Robert Anthony Bellamy](https://www.linkedin.com/in/robert-anthony-bellamy-baa80781)
##### Bio:

Robert is a Senior Software Engineer at NBCUniversal who is very passionate about delivering well architected open source solutions. His experience across a broad range of industries has seen him deliver user centric, fast performing solutions for a diverse client base.

He specializes in the CMS Drupal and is a core contributor to the project and other Open Source communities. He is a co-organizer of the Gotham Sass meetup and lead organizer for the DevOps Camp Camp (formerly DevOps summit) at The United Nations.

Prior to joining NBCUniversal Robert worked at NorthPoint Digital/EY and was a freelance web developer working primarily in the arts industry, helping artists and organizations leverage open source tools. 

Robert holds a Bachelor of Music in Double Bass Performance from The Manhattan School of Music.
##### Photo:

![Avatar](https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAVWAAAAJDAwMDFkN2ExLTFiYmEtNDJiZC1iMmI4LTE3MTFjM2ZiZmZhYw.jpg)

---

**Comment by skyfaerie** [comment]
Let's get this scheduled on the calendar!

**Comment by skyfaerie** [comment]
April's Sasshack/Workshop is scheduled! http://www.meetup.com/gothamsass/events/229027470/.
Closing this issue out :-)
