### ISSUE TITLE
Spot the difference: Visual Regression Testing for your SASS

### ISSUE THREAD

**Issue by ianyamey** [GothamSass/centralpark#8]
# Spot the difference: Visual Regression Testing for your SASS
## Type of Presentation (required)
- [x] Standard Length Talk _(20 or 30 mins)_
- [ ] Lightning Talk _(5 or 10 mins)_
- [ ] Workshop _(1.5-2hrs)_
## When would you ideally like to speak

March, April, May
## Description (required)

![](https://percy.io/images/example-window-overlay-bfa242b248b3be2e25e05ee5384e7173.png)

We write unit tests, feature tests and even behavior tests for the websites and apps that we work on. But how do we ensure that changes to our SASS/CSS don't introduce unintended visual bugs into our app?

This talk explains Visual Regression Testing, why it is important, and how we've used it at PolicyGenius to ensure that we can confidently change our stylesheets without stressing about unintended style changes leaking into our app.

Outline:
- Spot the difference
  - audience challenge, eg https://www.google.com/search?q=spot+the+difference&tbm=isch
- Examples of unintended CSS changes
  - real world examples of how innocuous changes to css may have repercussions elsewhere on the site
- Why do we write automated tests?
  - to catch regressions before they hit production
  - to give developers the confidence to make changes
  - to reduce manual QA
- What is a diff? What is a visual diff?
- Headless browsers
  - Automatically taking screenshots of your app
- How to use open source tools to build your own visual regression testing suite
  - Setting up PhantomCSS
- How to use Percy.io to setup visual regression testing in 5 minutes
- Bonus:
  - Why your designer should sign off on your pull requests
## Speaker Info (required)
- Name                     : Ian Yamey
- Location                 : Brooklyn, NY
- Contact                  : ian at policygenius dot com
- Preferred gender pronoun   : Him/He
##### Social Media:
- Twitter   : [@ianyamey](https://www.twitter.com/ianyamey)
- GitHub    : [ianyamey](https://www.github.com/ianyamey)
- Url(s)    : [policygenius.com](https://www.policygenius.com)
##### Bio:

I’m the CTO at PolicyGenius, finding consumer-first ways to simplify shopping for insurance online.
##### Photo:

![Photo of Ian](https://www.policygenius.com/assets/team-members/Ian.png)

**Comment by skyfaerie** [comment]
Hi Ian! Thanks for your submission! This talk sounds amazing! Hang tight, we'll shoot you an email soon.

**Comment by skyfaerie** [comment]
@ianyamey we've scheduled you for our April Meetup! Let us know what you think: http://www.meetup.com/gothamsass/events/229027223/
