### ISSUE TITLE
Web Component & Friends: Enabling Web Development processes that's more component-driven, modular, semantic, and accessible

### ISSUE THREAD

**Issue by lozandier** [GothamSass/centralpark#9]
## Web Component & Friends: Enabling Web Development processes that's more component-driven, modular, semantic, framework-agnostic, and accessible

Web Component & Friends: Enabling component-centeric development that's more modular,
accessible, and semantic
## Type of Presentation (required)

[x] Standard Length Talk _(20 or 30 mins)_

[ ] Lightning Talk _(5 or 10 mins)_

[x] Workshop _(1.5-2hrs)_
## When would you ideally like to speak

February/March
## Description
- Part 1: The 4 Fundamental Web Component specs; The Fundamentals before the abstractions
  - What are the suite of Web Component today
  - how they generally work
  - Common problems that Web Components explicitly solve
    - modularity & scoping problems that usually necessitate CSS naming conventions. 
    - Usability (a11y) & re-usability
  - The fundamental Web Component specs, and the browser support & caveats they have individually w/ CodePen examples
    - Template Tag
    - Custom elements
    - Shadow DOM
    - HTML Imports
  - Resources to find out more about Web Components
  - Finding Web Components to immediately use & how to use them in existing and new projects
  - Finding & using Web Components w/ Codepen
- Part 2: Polymer and other specs and tools that pair well with the standards related to Web Components
  - Polymer, The jQuery of Web Component in a good way: What that exactly means and what that means for Web professionals bein
    - What is Polymer, and what it provides in functionality and boost in productivity
    - Creating Web Components with Polymer
      - Markup enhancements
      - Styling with Web Components
  - Web Component Tester (WCT)
    - What is Web Component Tester & how to get started
  - CSS Variables
  - Push Promises (HTTP/2) 
  - Service Workers
- Part 3: Tips, Myths, and FAQs towards leveraging Web Components in the Real world
  - Best Practices Examples
    - Follow the F.I.R.S.T principles of developing components
      - Focused
      - Independent
      - Reusable
      - Small
      - Testable
    - Create leaf node Web Components: What that means, and how that's critical towards making 
      consistently reusable components.
  - Keyboard-first driven development of interactive, leaf-node components
  - What Web Component specs to have more caution using than others. 
  - Avoid components that defy being leaf nodes (presentational components) with how they handle data that can make the component not as framework-friendly as it can be
  - Myths Examples
    - React, CycleJS, and other component abstractions like Angular directives compared to Web Components are antagonistic technologies to invest in
    - It's too soon to use Web Components reliably
    - Explanation of common myths & misunderstanding of the Shadow DOM
    - DOM is slow, so why use new abstractions that continue to rely on 'em to build components  
    -  Web Components friendly frameworks such as Polymer and Angular 2 are slower/update slower (i.e. repainting performance ) than popular frameworks that leverage virtual-DOM such as React.  
      ## Speaker Info (required)
- Name                     : Kevin Lozandier
- Location                 : Brooklyn, NY
- Contact                  : lozandier@gmail.com
- Preferred gender pronoun   : Him
##### Social Media:
- Twitter   : [@kevinlozandier](https://twitter.com/KevinLozandier)
- GitHub    : [lozandier](https://github.com/lozandier)
##### Bio:

I’m an example bio. I'm an Billionaire CEO by day and a cape crusader by night. I AM BATMAN!
##### Photo:

*\* To Be Determined **

**Comment by rabellamy** [comment]
:+1:

**Comment by skyfaerie** [comment]
@lozandier a couple things: 
1) We need to cut your talk title down to fit meetup. What do you think? We hit the max char at this:
Web Components: Enabling Component-Driven, Modular, Semantic, Framework, Accessible Processes

2) This is a talk, yea? How long do you think it'll be? You have both Talk & Workshop selected; will there be some attendee interaction?

**Comment by lozandier** [comment]
I'd remove `framework-agnostic` frameworks altogether; `framework` in that
truncated version wouldn't make sense.

I primarily intend this to be a talk; but since my example pens I plan on
making can be manually done by attendees today as exercises; I see the
opportunity for this to be a workshop as well with minimal changes on my
part as far as how I've outlined what I planned for the outline thus far.

**Comment by lozandier** [comment]
I can discuss this with you in greater detail after this Thursday;  I have
a serious deadline to meet by the end of that day that'll limit my
opportunities to immediately respond to questions about this.

Does that restrict you in any way?

On Wed, Feb 10, 2016 at 4:46 PM, Kevin Lozandier lozandier@gmail.com
wrote:

> I'd remove `framework-agnostic` frameworks altogether; `framework` in that
> truncated version wouldn't make sense.
> 
> I primarily intend this to be a talk; but since my example pens I plan on
> making can be manually done by attendees today as exercises; I see the
> opportunity for this to be a workshop as well with minimal changes on my
> part as far as how I've outlined what I planned for the outline thus far.
> 
> On Wednesday, February 10, 2016, Aisha G notifications@github.com wrote:
> 
> > @lozandier https://github.com/lozandier a couple things:
> > 1) We need to cut your talk title down to fit meetup. What do you think?
> > We hit the max char at this:
> > Web Components: Enabling Component-Driven, Modular, Semantic, Framework,
> > Accessible Processes
> > 
> > 2) This is a talk, yea? How long do you think it'll be? You have both
> > Talk & Workshop selected; will there be some attendee interaction?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/GothamSass/centralpark/issues/9#issuecomment-182593771
> > .

## 

Kevin Lozandier
lozandier@gmail.com lozandier@gmail.com

**Comment by skyfaerie** [comment]
Not at all. Meet those deadlines. We'll fill in whatever's missing later. Thanks again and Good Luck! 

I mis-typed. I meant to keep the word agnostic, not framework. That makes zero sense. Let me know what you think.

**Comment by lozandier** [comment]
I'm available again if you want to discuss this further.

**Comment by skyfaerie** [comment]
We're good to go! You can view meetup details [here](http://www.meetup.com/gothamsass/events/228708042/).
